-- MySQL Script generated by MySQL Workbench
-- Thu May  7 23:05:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema final_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema final_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `final_db`.`studyroom`
-- -----------------------------------------------------
CREATE TABLE `studyroom` (
  `studyroom_id` INT NOT NULL,
  `studyroom_name` VARCHAR(45) NOT NULL,
  `studyroom_admin_id` INT NOT NULL,
  `studyroom_ann` VARCHAR(200) NULL,
  `studyroom_count` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_db`.`users`
-- -----------------------------------------------------
CREATE TABLE `users` (
  `user_id` INT NOT NULL,
  `user_pass` VARCHAR(20) NOT NULL,
  `user_nickname` VARCHAR(20) NULL,
  `user_fname` VARCHAR(20) NOT NULL,
  `user_lname` VARCHAR(20) NOT NULL,
  `user_email` VARCHAR(20) NOT NULL,
  `user_sign` VARCHAR(45) NULL,
  `user_auth` INT NULL,
  `user_room_id` INT NULL,
  `user_avatar` VARCHAR(200) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_db`.`tasks`
-- -----------------------------------------------------
CREATE TABLE `tasks` (
  `task_id` INT NOT NULL,
  `task_user_id` INT NOT NULL,
  `task_name` VARCHAR(45) NOT NULL,
  `task_start` TIME NOT NULL,
  `task_end` TIME NULL,
  `task_aborted` INT NULL)
ENGINE = InnoDB;

ALTER TABLE `studyroom`
    ADD PRIMARY KEY (`studyroom_id`);

ALTER TABLE `users`
    ADD PRIMARY KEY (`user_id`);

ALTER TABLE `tasks`
    ADD PRIMARY KEY (`task_id`);

ALTER TABLE `studyroom`
    MODIFY `studyroom_id` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `users`
    MODIFY `user_id` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `tasks`
    MODIFY `task_id` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `studyroom`
    ADD CONSTRAINT `fk_studyroom_users1`
    FOREIGN KEY (`studyroom_admin_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE `users`
    ADD CONSTRAINT `fk_users_studyroom`
    FOREIGN KEY (`user_room_id`)
    REFERENCES `studyroom` (`studyroom_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE `tasks`
    ADD CONSTRAINT `fk_tasks_users1`
    FOREIGN KEY (`task_user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
